version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:14.15.4
    steps:
      -checkout
      -restore_cache:
          keys: dependencies-cache-{{ checksum "package.json" }}
      -run:
          name: Install dependencies
          command: npm install
      -save_cache:
          paths:
            - ./node_modules
          key: dependencies-cache-{{ checksum "package.json" }}
      -run:
          name: Build React App
          command: npm run build
      -save_cache:
          paths:
            - ./build
          key: build-cache-{{ .Branch }}
      -run:
          name: Deploy to Netlify
          command: ./node_modules/.bin/netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_ACCESS_TOKEN --prod --dir=build
workflows:
  version: 2
  build-deploy:
    jobs:
      -build:
          filters:
            branches:
              only: master

